$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1528362641668.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7721eb65e46f451dbc3747bc3c70d1f4",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"84b45c3e04544a91bfbfc56a8379ed84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x339933FF},
            "location":{
              "x":220,
              "y":110},
            "size":{
              "width":380,
              "height":284}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4d30fece0ae4725b514cc7bcbaa4182",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x339933FF},
                "location":{
                  "x":220,
                  "y":110},
                "size":{
                  "width":380,
                  "height":284}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"23ba4006b62f4a52aeaa0d956eb99d0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":200},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90863a157db947ce85aebee9a480274c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":200},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"caabfe4ea31b4f40a1f29b52277c7ac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":264,
              "y":234},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d54109fc01e84f2ab9ef001b7671a94b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":264,
                  "y":234},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c09c5da96ed47e7919692ceab742c1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":200},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84a0b192ceb24e2e8cdcb7292ca0acc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":200},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u6.png"}},
{
          "id":"de773c98af024f68aec90064bc969a96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":234},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f5cf3835f8e48deaa4dc50178d3ccbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":234},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u6.png"}},
{
          "id":"a93832b98a5847ed9e00c133cac8940f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":274},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b55fc94705aa4fcfa0638cdbf8b68230",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":274},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c79741e8c95841fd85e0ebc45c69d070",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":274},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b362ae0d1fcc426b91434f3a730d45eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":274},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bb35e91fcde54526a64101049bd1fa34",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":476,
              "y":274},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"313357edbe13429fb23529a0f4d6eb23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":476,
                  "y":274},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6d9fe76e27054255aa797f86eabe542c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":274},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e9c05ee595f4ea9b39ce392eac2d0db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":274},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be19b71e83f348d5be5120a0d3d776d6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":320},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"13636cba2278403a90df821f87d8239b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":320},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"afb7a79f37ee4cefa110571d77325038",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":273,
              "y":142},
            "size":{
              "width":274,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bb6a2ccf62046e59bae4e3c0ac1dc7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":273,
                  "y":142},
                "size":{
                  "width":274,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a0fccd83f9241aca90cf75bd48a121e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":116},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48c8a6db72c44c2f97a69345bc403f77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":116},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u22.png"}},
{
          "id":"066b666c97194908a4e86a47f920997f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":350},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92db01b236784b83b2fbc13f3f46d0c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":350},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "84b45c3e04544a91bfbfc56a8379ed84":{
      "scriptId":"u0"},
    "b4d30fece0ae4725b514cc7bcbaa4182":{
      "scriptId":"u1"},
    "23ba4006b62f4a52aeaa0d956eb99d0b":{
      "scriptId":"u2"},
    "90863a157db947ce85aebee9a480274c":{
      "scriptId":"u3"},
    "caabfe4ea31b4f40a1f29b52277c7ac2":{
      "scriptId":"u4"},
    "d54109fc01e84f2ab9ef001b7671a94b":{
      "scriptId":"u5"},
    "9c09c5da96ed47e7919692ceab742c1d":{
      "scriptId":"u6"},
    "84a0b192ceb24e2e8cdcb7292ca0acc6":{
      "scriptId":"u7"},
    "de773c98af024f68aec90064bc969a96":{
      "scriptId":"u8"},
    "3f5cf3835f8e48deaa4dc50178d3ccbe":{
      "scriptId":"u9"},
    "a93832b98a5847ed9e00c133cac8940f":{
      "scriptId":"u10"},
    "b55fc94705aa4fcfa0638cdbf8b68230":{
      "scriptId":"u11"},
    "c79741e8c95841fd85e0ebc45c69d070":{
      "scriptId":"u12"},
    "b362ae0d1fcc426b91434f3a730d45eb":{
      "scriptId":"u13"},
    "bb35e91fcde54526a64101049bd1fa34":{
      "scriptId":"u14"},
    "313357edbe13429fb23529a0f4d6eb23":{
      "scriptId":"u15"},
    "6d9fe76e27054255aa797f86eabe542c":{
      "scriptId":"u16"},
    "7e9c05ee595f4ea9b39ce392eac2d0db":{
      "scriptId":"u17"},
    "be19b71e83f348d5be5120a0d3d776d6":{
      "scriptId":"u18"},
    "13636cba2278403a90df821f87d8239b":{
      "scriptId":"u19"},
    "afb7a79f37ee4cefa110571d77325038":{
      "scriptId":"u20"},
    "0bb6a2ccf62046e59bae4e3c0ac1dc7e":{
      "scriptId":"u21"},
    "2a0fccd83f9241aca90cf75bd48a121e":{
      "scriptId":"u22"},
    "48c8a6db72c44c2f97a69345bc403f77":{
      "scriptId":"u23"},
    "066b666c97194908a4e86a47f920997f":{
      "scriptId":"u24"},
    "92db01b236784b83b2fbc13f3f46d0c2":{
      "scriptId":"u25"}}});