@startuml 用例图
left to right direction
:User: 
:学生: as student
:任课教师: as teacher
:院系管理员: as admin
package 用户基本功能{
    (查看用户信息) as showUser
    (修改用户信息) as updateUser
    (修改密码) as updatePwd
    (登录) as login
    (登出) as logout
    User -up-> showUser
    User -up-> updateUser
    User -up-> updatePwd
    User -up-> login
    User -up-> logout
}
package 业务用例集{
    (选课) as singCourse
    (课程列表) as getClassList
    (学生列表) as GetStudents
    (批改成绩) as setGrade
    (添加课程实验) as addCourseTask
    (编辑课程实验) as ediCourseTask
    (删除课程实验) as delCourseTask
    (添加课程) as addCourse
    (编辑课程) as ediCourse
    (删除课程) as delCourse
    student --> getClassList
    User --> singCourse
    teacher --> GetStudents
    teacher --> setGrade
    admin --> addCourseTask
    admin --> ediCourseTask
    admin --> delCourseTask
    admin --> addCourse
    admin --> ediCourse
    admin --> delCourse
}
student -up-|> User
teacher -up-|> User
admin -up-|> User
@enduml