@startuml 期末考试流程
|#efe|教务处|
start
:安排考试;
:考试安排表;
|教师|
:出卷;
split
    :AB试卷;
split again
    :打印审批表;
    |#efe|系主任|
    :审批签字;
    :打印审批表;
end split
|#efe|教务处|
:打印试卷;
:试卷;
|学生|
:参加考试;
:答卷;
|教师|
:阅卷出成绩;
split
    :成绩单;
    |#efe|教务处|
    if (有不及格?) then(有)
        :安排补考;
    else()
        stop
    endif
    split
        :补考安排表;
        stop
    split again

    end split
split again
    |教师|
    :答卷;
    :装订存档;
end split
|教师|
fork
    : ;
end fork
:期末流程结束;
@enduml