@startuml 图书查询(条件查询)
title 图书查询(条件查询)
hide footbox
skinparam backgroundColor #ded
actor borrower
boundary 图书查询窗口
activate borrower
activate 图书查询窗口
borrower -> 图书查询窗口: 输入检索条件
图书查询窗口 -> 图书查询窗口: 验证输入信息
borrower -> 图书查询窗口: 点击查看详情
database book
图书查询窗口 -> book: 查询图书
activate book
book --> 图书查询窗口: 返回图书
@enduml

@startuml 图书查询(全部查询)
title 图书查询(全部查询)
skinparam backgroundColor #ded
hide footbox
actor borrower
boundary 图书查询窗口
database book
activate borrower
borrower -> 图书查询窗口: 点击查询
activate 图书查询窗口
图书查询窗口 -> book: 获取图书
activate book
book --> 图书查询窗口: 返回图书
deactivate book
@enduml

@startuml 借书
skinparam backgroundColor #eee
hide footbox
actor 图书管理员
boundary 借书办理窗口
database borrower
database bookDetList
database bookDetListInfo
activate 图书管理员
activate 借书办理窗口
图书管理员 -> 借书办理窗口: 输入借阅者信息
借书办理窗口 -> borrower: 查询借阅者信息
activate borrower
borrower --> 借书办理窗口: borrower
deactivate borrower
图书管理员 -> 借书办理窗口: 判断是否符合借阅要求
[-> 图书管理员: 查询将借阅的图书信息
图书管理员 -> 图书管理员: 检查图书是否满足借阅条件
图书管理员 -> 借书办理窗口: 填写借书单并提交
借书办理窗口 -> bookDetList: 保存借书单
activate bookDetList
bookDetList -> bookDetListInfo: 保存详细条目
activate bookDetListInfo
bookDetListInfo-->bookDetList: success
deactivate bookDetListInfo
bookDetList --> 借书办理窗口: success
deactivate bookDetList
@enduml

@startuml 续借
skinparam backgroundColor #eef
hide footbox
actor 图书管理员
boundary 续借办理窗口
collections bookDetLists
database bookDetList
activate 图书管理员
activate 续借办理窗口
[-> 图书管理员: 检查书籍完整性
[<-- 图书管理员: 违规处理
图书管理员 -> 续借办理窗口: 输入借阅者借阅证
续借办理窗口 -> bookDetLists: 查询借阅者借书单
activate bookDetLists
bookDetLists --> 续借办理窗口:bookDetLists
图书管理员 -> 图书管理员: 点击借书单详情,验证是否逾期
[<-- 图书管理员: 违规处理
图书管理员 -> 续借办理窗口: 确认续借
续借办理窗口 -> bookDetList: 更新借书单借书期限
activate bookDetList
bookDetList --> 续借办理窗口: success
deactivate bookDetList
deactivate bookDetLists
@enduml

@startuml 还书
skinparam backgroundColor #eee
hide footbox
actor 图书管理员
boundary 还书办理窗口
collections bookDetLists
database borrowHis
activate 图书管理员
activate 还书办理窗口
[-> 图书管理员: 检查书籍完整性
[<-- 图书管理员: 违规处理
图书管理员 -> 还书办理窗口: 输入借阅者借阅证
还书办理窗口 -> bookDetLists: 查询借书单集合
activate bookDetLists
bookDetLists -> 还书办理窗口: bookDetLists
图书管理员 -> 图书管理员: 查找对应借书单,检查是否逾期
[<-- 图书管理员: 违规处理
图书管理员 -> 还书办理窗口: 确认还书
还书办理窗口 -> borrowHis: 保存借书历史
activate borrowHis
borrowHis --> bookDetLists: success
deactivate borrowHis
bookDetLists->bookDetLists: 删除对应书单
bookDetLists-->还书办理窗口: success
deactivate bookDetLists
@enduml

@startuml 违规处理
skinparam backgroundColor #eee
hide footbox
actor 图书管理员
boundary 违规处罚窗口
collections borrowHis
database ticket
activate 图书管理员
activate 违规处罚窗口
[->图书管理员: 违规信息
图书管理员->图书管理员: 决策处理办法
图书管理员->违规处罚窗口: 记录并提交
违规处罚窗口->borrowHis: 保存借书记录
activate borrowHis
borrowHis->ticket: 生成ticket,传入借书单号
activate ticket
ticket-->borrowHis: success
deactivate ticket
borrowHis->borrowHis:flag=ture 
borrowHis-->违规处罚窗口: success
@enduml

@startuml 书目管理(增加图书)
skinparam backgroundColor #eee
title 增加图书
hide footbox
actor 图书管理员
boundary 书目管理窗口
entity adimn
database book
activate 图书管理员
activate 书目管理窗口
activate adimn
图书管理员->书目管理窗口: 选择增加图书选项
书目管理窗口->图书管理员: 弹出身份验证页面
图书管理员->书目管理窗口: 输入图书管理员密码
书目管理窗口->书目管理窗口: 验证输入有效性
书目管理窗口->adimn: 比较身份信息
书目管理窗口->图书管理员: 显示身份验证操作结果及下一步界面
图书管理员->书目管理窗口: 填写图书详细信息,检查并提交
书目管理窗口->book: 保存书籍信息
activate book
book->书目管理窗口: success
deactivate book
@enduml



@startuml 书目管理(修改图书)
skinparam backgroundColor #eee
title 修改图书
hide footbox
actor 图书管理员
boundary 书目管理窗口
entity adimn
database book
activate 图书管理员
activate 书目管理窗口
activate adimn
图书管理员->书目管理窗口: 点击修改图书
书目管理窗口->图书管理员: 弹出身份验证页面
图书管理员->书目管理窗口: 输入管理密码
书目管理窗口->adimn: 验证管理员权限
书目管理窗口->图书管理员: 显示验证结果
图书管理员->书目管理窗口: 输入需修改图书详细
书目管理窗口->book: 查询书籍
activate book
book-->书目管理窗口: book
deactivate book
图书管理员->书目管理窗口: 修改书籍信息
书目管理窗口->书目管理窗口: 验证修改项合法性
书目管理窗口->book: 更新书籍
activate book
book-->书目管理窗口: success
deactivate book
@enduml



@startuml 书目管理(删除图书)
skinparam backgroundColor #eee
title 删除图书
hide footbox
actor 图书管理员
boundary 书目管理窗口
entity adimn
database book
activate 图书管理员
activate 书目管理窗口
activate adimn
图书管理员->书目管理窗口: 点击修改图书
书目管理窗口->图书管理员: 弹出身份验证页面
图书管理员->书目管理窗口: 输入管理密码
书目管理窗口->adimn: 验证管理员权限
书目管理窗口->图书管理员: 显示验证结果
图书管理员->书目管理窗口: 输入需修改图书详细
书目管理窗口->book: 查询书籍
activate book
book->书目管理窗口: 返回书籍
deactivate book
图书管理员->书目管理窗口: 确认删除
书目管理窗口->book: 删除书籍
activate book
book->书目管理窗口: success
deactivate book
@enduml

@startuml 系统管理
skinparam backgroundColor #eee
hide footbox
actor 超级管理员
boundary 系统管理界面
database borrower
activate 超级管理员
activate 系统管理界面
超级管理员->系统管理界面: 输入用户查找条件
系统管理界面->borrower: 查找符合条件的用户集合
activate borrower
borrower-->系统管理界面: 返回并显示查询结果
deactivate borrower
超级管理员->系统管理界面: 选择用户
系统管理界面->系统管理界面: 显示用户详细信息
超级管理员->系统管理界面: 修改用户'stauts'属性并点击提交
系统管理界面->超级管理员: 弹出权限验证
超级管理员->系统管理界面: 输入root密码
系统管理界面->系统管理界面: 验证权限
系统管理界面->borrower: 更新用户信息
activate borrower
borrower-->系统管理界面: success
deactivate borrower
@enduml

@startuml 账户设置(用户自身)
skinparam backgroundColor #eee
hide footbox
actor 借阅者
boundary 账户设置界面
database borrower
activate 借阅者
activate 账户设置界面
借阅者->账户设置界面: 点击个人头像
账户设置界面->借阅者: 显示个人信息
借阅者->账户设置界面: 点击并修改个人信息
账户设置界面->借阅者: 弹出身份验证
借阅者->账户设置界面: 输入密码
账户设置界面->账户设置界面: 验证提交信息合法性
账户设置界面->borrower: 更新借阅者信息
activate borrower
borrower->账户设置界面: success
deactivate borrower
@enduml
