@startuml 图书管理系统用例图
skinparam packageStyle rectangle

:借阅者: as Borrower
:游客: as Visitor
:图书管理员: as Admin
:超级管理员: as root

rectangle 图书管理系统{
    (图书查询) as query

    (账户设置) as sett_  

    (借书) as bor_
    (续借) as renew
    (还书) as ret_
    (违规处理) as fine
    (书目管理) as bookI_

    root -right-> (系统管理)
}
' 用例之间的关系
bor_ ..> query:<<include>>
ret_ <.. fine:<<extend>>
bor_ <.. renew:<<extend>>
renew <.. fine:<<extend>>

' 外部实体之间的关系

Borrower --|> Visitor
' Admin --|> Borrower
root --|> Admin
'图书管理员和借阅者之间似乎不应该有泛化关系，管理者不能既当运动员，又当裁判员。
' 用例与参与的外部实体之间的关系
Visitor --> query
Borrower --> sett_

Admin --> bor_
Admin --> ret_
Admin --> bookI_
left to right direction

@enduml