'几个比较简单的用例不再次分析流程

@startuml 借书用例流程图
|图书管理员|
start
:[查询图书];
if (书籍库存>=1?) then(no)
    end
else(yes)
    :查询读者信息;
    if (读者信用分过低?) then(yes)
        end
    ELSE(no)
        :提交借书信息;
    endif
endif
|系统|
:生成借书单;
:相关书籍库存-1;
end
@enduml



@startuml 还书用例流程图
|图书管理员|
start
:查询读者信息;
if (书籍遗失) then(yes)
    :[违规处罚];
    end
else(no)
    :获取借书单信息与归还书籍进行比对;
    if (归还书籍与借书单所示书籍匹配?) then(no)
        :再次确认归还书籍与借书单信息;
        if(多次检查仍然无法匹配?) then(yes)
            :标记为问题借书单;
            :暂时扣留书籍;
            :报告错误;
            |系统|
            :置借书单状态为'错误';
            :发送错误报告;
            end
        else(yes)
        endif
    else(no)
    endif
    |图书管理员|
    :检查书籍完整性;
    if(书籍完整?) then(no)
        :[违规处罚];
        end
    else(yes)
        :提交还书信息;
    endif
    |系统|
    :更改借书单状态为'归还';
    :用户信息追加:\n借阅信息(正常归还);
    :相关书籍库存+1;
    end
endif
@enduml



@startuml 续借用例流程图
|图书管理员|
start
:查询读者信息;
if (确认书籍是否遗失) then(yes)
    :[违规处罚];
    end
else(no)
    :获取借书单信息与续借书籍进行比对;
    if (归还书籍与借书单所示书籍匹配?) then(no)
        :再次确认续借书籍与借书单信息;
        if(多次检查仍然无法匹配?) then(yes)
            :标记为问题借书单;
            :暂时扣留书籍;
            :报告错误;
            |系统|
            :置借书单状态为'错误';
            :发送错误报告;
            end
        else(yes)
        endif
    else(no)
    endif
    |图书管理员|
    :检查书籍完整性;
    if(书籍完整?) then(no)
        :[违规处罚];
        end
    else(yes)
        :提交续借信息;
    endif
    |系统|
    :更改借书单状态为'续借';
    :书单追加信息:\n续借办理时间;
    :刷新借书单信息:\n      可借天数;
    end
endif
@enduml



@startuml 书目管理用例流程图
|图书管理员\系统管理员|
start
split
    :查询图书;
    split
        :进入图书编辑页面;
        repeat
        :修改图书信息;
        :提交修改;
        |图书管理员\系统管理员|
        repeat while (修改信息符不合法?)
    split again
        :点击删除图书;
        repeat
        :输入超级管理员密码;
        repeat while (密码不正确?)
    end split
split again
    :进入添加书目页面;
    while(流程结束?)
    :录入图书信息;
    :提交图书信息;
    |系统|
    if (书籍ISBN号已存在?) then(no)
        if(书籍信息录入正确?) then(no)
            :提示信息:\n输入信息格式不正确;
        else(yes)
            :添加书籍信息;
            :更新书目;
            end
        endif
    else(yes)
        :提示信息:\nISBN号已存在;
    endif
    :返回输入页面;
    endwhile
    |图书管理员\系统管理员|
    end
end split
end 
@enduml