package org.sinmem.bean;

public class Admin  extends User{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.userID
	 * @mbggenerated
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.pwd
	 * @mbggenerated
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.userType
	 * @mbggenerated
	 */
	private Integer usertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.instituteNo
	 * @mbggenerated
	 */
	private String instituteno;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.userID
	 * @return  the value of admin.userID
	 * @mbggenerated
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.userID
	 * @param userid  the value for admin.userID
	 * @mbggenerated
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.pwd
	 * @return  the value of admin.pwd
	 * @mbggenerated
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.pwd
	 * @param pwd  the value for admin.pwd
	 * @mbggenerated
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd == null ? null : pwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.name
	 * @return  the value of admin.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.name
	 * @param name  the value for admin.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.userType
	 * @return  the value of admin.userType
	 * @mbggenerated
	 */
	public Integer getUsertype() {
		return usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.userType
	 * @param usertype  the value for admin.userType
	 * @mbggenerated
	 */
	public void setUsertype(Integer usertype) {
		this.usertype = usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.instituteNo
	 * @return  the value of admin.instituteNo
	 * @mbggenerated
	 */
	public String getInstituteno() {
		return instituteno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.instituteNo
	 * @param instituteno  the value for admin.instituteNo
	 * @mbggenerated
	 */
	public void setInstituteno(String instituteno) {
		this.instituteno = instituteno == null ? null : instituteno.trim();
	}
}