package org.sinmem.bean;

import java.util.Date;

public class Cexperiments {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiments.experimentscoresNo
	 * @mbggenerated
	 */
	private String experimentscoresno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiments.experimentNo
	 * @mbggenerated
	 */
	private String experimentno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiments.userID
	 * @mbggenerated
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiments.oder
	 * @mbggenerated
	 */
	private Integer oder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiments.title
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiments.info
	 * @mbggenerated
	 */
	private String info;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiments.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiments.date
	 * @mbggenerated
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiments.score
	 * @mbggenerated
	 */
	private Float score;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiments.experimentscoresNo
	 * @return  the value of cexperiments.experimentscoresNo
	 * @mbggenerated
	 */
	public String getExperimentscoresno() {
		return experimentscoresno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiments.experimentscoresNo
	 * @param experimentscoresno  the value for cexperiments.experimentscoresNo
	 * @mbggenerated
	 */
	public void setExperimentscoresno(String experimentscoresno) {
		this.experimentscoresno = experimentscoresno == null ? null : experimentscoresno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiments.experimentNo
	 * @return  the value of cexperiments.experimentNo
	 * @mbggenerated
	 */
	public String getExperimentno() {
		return experimentno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiments.experimentNo
	 * @param experimentno  the value for cexperiments.experimentNo
	 * @mbggenerated
	 */
	public void setExperimentno(String experimentno) {
		this.experimentno = experimentno == null ? null : experimentno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiments.userID
	 * @return  the value of cexperiments.userID
	 * @mbggenerated
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiments.userID
	 * @param userid  the value for cexperiments.userID
	 * @mbggenerated
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiments.oder
	 * @return  the value of cexperiments.oder
	 * @mbggenerated
	 */
	public Integer getOder() {
		return oder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiments.oder
	 * @param oder  the value for cexperiments.oder
	 * @mbggenerated
	 */
	public void setOder(Integer oder) {
		this.oder = oder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiments.title
	 * @return  the value of cexperiments.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiments.title
	 * @param title  the value for cexperiments.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiments.info
	 * @return  the value of cexperiments.info
	 * @mbggenerated
	 */
	public String getInfo() {
		return info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiments.info
	 * @param info  the value for cexperiments.info
	 * @mbggenerated
	 */
	public void setInfo(String info) {
		this.info = info == null ? null : info.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiments.address
	 * @return  the value of cexperiments.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiments.address
	 * @param address  the value for cexperiments.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiments.date
	 * @return  the value of cexperiments.date
	 * @mbggenerated
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiments.date
	 * @param date  the value for cexperiments.date
	 * @mbggenerated
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiments.score
	 * @return  the value of cexperiments.score
	 * @mbggenerated
	 */
	public Float getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiments.score
	 * @param score  the value for cexperiments.score
	 * @mbggenerated
	 */
	public void setScore(Float score) {
		this.score = score;
	}
}