package org.sinmem.bean;

public class Cexperiment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiment.experimentNo
	 * @mbggenerated
	 */
	private String experimentno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiment.oder
	 * @mbggenerated
	 */
	private Integer oder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiment.title
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiment.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cexperiment.courseNo
	 * @mbggenerated
	 */
	private String courseno;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiment.experimentNo
	 * @return  the value of cexperiment.experimentNo
	 * @mbggenerated
	 */
	public String getExperimentno() {
		return experimentno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiment.experimentNo
	 * @param experimentno  the value for cexperiment.experimentNo
	 * @mbggenerated
	 */
	public void setExperimentno(String experimentno) {
		this.experimentno = experimentno == null ? null : experimentno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiment.oder
	 * @return  the value of cexperiment.oder
	 * @mbggenerated
	 */
	public Integer getOder() {
		return oder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiment.oder
	 * @param oder  the value for cexperiment.oder
	 * @mbggenerated
	 */
	public void setOder(Integer oder) {
		this.oder = oder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiment.title
	 * @return  the value of cexperiment.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiment.title
	 * @param title  the value for cexperiment.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiment.address
	 * @return  the value of cexperiment.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiment.address
	 * @param address  the value for cexperiment.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cexperiment.courseNo
	 * @return  the value of cexperiment.courseNo
	 * @mbggenerated
	 */
	public String getCourseno() {
		return courseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cexperiment.courseNo
	 * @param courseno  the value for cexperiment.courseNo
	 * @mbggenerated
	 */
	public void setCourseno(String courseno) {
		this.courseno = courseno == null ? null : courseno.trim();
	}
}