package org.sinmem.bean;

public class Clazz {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column clazz.clazzNo
	 * @mbggenerated
	 */
	private String clazzno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column clazz.ClazzName
	 * @mbggenerated
	 */
	private String clazzname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column clazz.education
	 * @mbggenerated
	 */
	private Integer education;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column clazz.majorNo
	 * @mbggenerated
	 */
	private String majorno;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clazz.clazzNo
	 * @return  the value of clazz.clazzNo
	 * @mbggenerated
	 */
	public String getClazzno() {
		return clazzno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clazz.clazzNo
	 * @param clazzno  the value for clazz.clazzNo
	 * @mbggenerated
	 */
	public void setClazzno(String clazzno) {
		this.clazzno = clazzno == null ? null : clazzno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clazz.ClazzName
	 * @return  the value of clazz.ClazzName
	 * @mbggenerated
	 */
	public String getClazzname() {
		return clazzname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clazz.ClazzName
	 * @param clazzname  the value for clazz.ClazzName
	 * @mbggenerated
	 */
	public void setClazzname(String clazzname) {
		this.clazzname = clazzname == null ? null : clazzname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clazz.education
	 * @return  the value of clazz.education
	 * @mbggenerated
	 */
	public Integer getEducation() {
		return education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clazz.education
	 * @param education  the value for clazz.education
	 * @mbggenerated
	 */
	public void setEducation(Integer education) {
		this.education = education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column clazz.majorNo
	 * @return  the value of clazz.majorNo
	 * @mbggenerated
	 */
	public String getMajorno() {
		return majorno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column clazz.majorNo
	 * @param majorno  the value for clazz.majorNo
	 * @mbggenerated
	 */
	public void setMajorno(String majorno) {
		this.majorno = majorno == null ? null : majorno.trim();
	}
}