package org.sinmem.bean;

public class Course {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.courseNo
	 * @mbggenerated
	 */
	private String courseno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.courseName
	 * @mbggenerated
	 */
	private String coursename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.creditHour
	 * @mbggenerated
	 */
	private Integer credithour;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.courseHour
	 * @mbggenerated
	 */
	private Integer coursehour;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.priorCourse
	 * @mbggenerated
	 */
	private String priorcourse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.majorNo
	 * @mbggenerated
	 */
	private String majorno;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.courseNo
	 * @return  the value of course.courseNo
	 * @mbggenerated
	 */
	public String getCourseno() {
		return courseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.courseNo
	 * @param courseno  the value for course.courseNo
	 * @mbggenerated
	 */
	public void setCourseno(String courseno) {
		this.courseno = courseno == null ? null : courseno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.courseName
	 * @return  the value of course.courseName
	 * @mbggenerated
	 */
	public String getCoursename() {
		return coursename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.courseName
	 * @param coursename  the value for course.courseName
	 * @mbggenerated
	 */
	public void setCoursename(String coursename) {
		this.coursename = coursename == null ? null : coursename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.creditHour
	 * @return  the value of course.creditHour
	 * @mbggenerated
	 */
	public Integer getCredithour() {
		return credithour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.creditHour
	 * @param credithour  the value for course.creditHour
	 * @mbggenerated
	 */
	public void setCredithour(Integer credithour) {
		this.credithour = credithour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.courseHour
	 * @return  the value of course.courseHour
	 * @mbggenerated
	 */
	public Integer getCoursehour() {
		return coursehour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.courseHour
	 * @param coursehour  the value for course.courseHour
	 * @mbggenerated
	 */
	public void setCoursehour(Integer coursehour) {
		this.coursehour = coursehour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.priorCourse
	 * @return  the value of course.priorCourse
	 * @mbggenerated
	 */
	public String getPriorcourse() {
		return priorcourse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.priorCourse
	 * @param priorcourse  the value for course.priorCourse
	 * @mbggenerated
	 */
	public void setPriorcourse(String priorcourse) {
		this.priorcourse = priorcourse == null ? null : priorcourse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.majorNo
	 * @return  the value of course.majorNo
	 * @mbggenerated
	 */
	public String getMajorno() {
		return majorno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.majorNo
	 * @param majorno  the value for course.majorNo
	 * @mbggenerated
	 */
	public void setMajorno(String majorno) {
		this.majorno = majorno == null ? null : majorno.trim();
	}
}