package org.sinmem.bean;

public class Courseclass {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column courseclass.courseNo
	 * @mbggenerated
	 */
	private String courseno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column courseclass.cClassNo
	 * @mbggenerated
	 */
	private String cclassno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column courseclass.number
	 * @mbggenerated
	 */
	private Integer number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column courseclass.count
	 * @mbggenerated
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column courseclass.term
	 * @mbggenerated
	 */
	private Integer term;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column courseclass.time
	 * @mbggenerated
	 */
	private Integer time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column courseclass.teacherNo
	 * @mbggenerated
	 */
	private String teacherno;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column courseclass.courseNo
	 * @return  the value of courseclass.courseNo
	 * @mbggenerated
	 */
	public String getCourseno() {
		return courseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column courseclass.courseNo
	 * @param courseno  the value for courseclass.courseNo
	 * @mbggenerated
	 */
	public void setCourseno(String courseno) {
		this.courseno = courseno == null ? null : courseno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column courseclass.cClassNo
	 * @return  the value of courseclass.cClassNo
	 * @mbggenerated
	 */
	public String getCclassno() {
		return cclassno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column courseclass.cClassNo
	 * @param cclassno  the value for courseclass.cClassNo
	 * @mbggenerated
	 */
	public void setCclassno(String cclassno) {
		this.cclassno = cclassno == null ? null : cclassno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column courseclass.number
	 * @return  the value of courseclass.number
	 * @mbggenerated
	 */
	public Integer getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column courseclass.number
	 * @param number  the value for courseclass.number
	 * @mbggenerated
	 */
	public void setNumber(Integer number) {
		this.number = number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column courseclass.count
	 * @return  the value of courseclass.count
	 * @mbggenerated
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column courseclass.count
	 * @param count  the value for courseclass.count
	 * @mbggenerated
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column courseclass.term
	 * @return  the value of courseclass.term
	 * @mbggenerated
	 */
	public Integer getTerm() {
		return term;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column courseclass.term
	 * @param term  the value for courseclass.term
	 * @mbggenerated
	 */
	public void setTerm(Integer term) {
		this.term = term;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column courseclass.time
	 * @return  the value of courseclass.time
	 * @mbggenerated
	 */
	public Integer getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column courseclass.time
	 * @param time  the value for courseclass.time
	 * @mbggenerated
	 */
	public void setTime(Integer time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column courseclass.teacherNo
	 * @return  the value of courseclass.teacherNo
	 * @mbggenerated
	 */
	public String getTeacherno() {
		return teacherno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column courseclass.teacherNo
	 * @param teacherno  the value for courseclass.teacherNo
	 * @mbggenerated
	 */
	public void setTeacherno(String teacherno) {
		this.teacherno = teacherno == null ? null : teacherno.trim();
	}
}