package org.sinmem.bean;

public class Experimentscores {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentscores.experimentscoresNo
	 * @mbggenerated
	 */
	private String experimentscoresno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentscores.experimentNo
	 * @mbggenerated
	 */
	private String experimentno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentscores.courseNo
	 * @mbggenerated
	 */
	private String courseno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentscores.cClassNo
	 * @mbggenerated
	 */
	private String cclassno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentscores.studentID
	 * @mbggenerated
	 */
	private String studentid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentscores.experimentscoresNo
	 * @return  the value of experimentscores.experimentscoresNo
	 * @mbggenerated
	 */
	public String getExperimentscoresno() {
		return experimentscoresno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentscores.experimentscoresNo
	 * @param experimentscoresno  the value for experimentscores.experimentscoresNo
	 * @mbggenerated
	 */
	public void setExperimentscoresno(String experimentscoresno) {
		this.experimentscoresno = experimentscoresno == null ? null : experimentscoresno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentscores.experimentNo
	 * @return  the value of experimentscores.experimentNo
	 * @mbggenerated
	 */
	public String getExperimentno() {
		return experimentno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentscores.experimentNo
	 * @param experimentno  the value for experimentscores.experimentNo
	 * @mbggenerated
	 */
	public void setExperimentno(String experimentno) {
		this.experimentno = experimentno == null ? null : experimentno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentscores.courseNo
	 * @return  the value of experimentscores.courseNo
	 * @mbggenerated
	 */
	public String getCourseno() {
		return courseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentscores.courseNo
	 * @param courseno  the value for experimentscores.courseNo
	 * @mbggenerated
	 */
	public void setCourseno(String courseno) {
		this.courseno = courseno == null ? null : courseno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentscores.cClassNo
	 * @return  the value of experimentscores.cClassNo
	 * @mbggenerated
	 */
	public String getCclassno() {
		return cclassno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentscores.cClassNo
	 * @param cclassno  the value for experimentscores.cClassNo
	 * @mbggenerated
	 */
	public void setCclassno(String cclassno) {
		this.cclassno = cclassno == null ? null : cclassno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentscores.studentID
	 * @return  the value of experimentscores.studentID
	 * @mbggenerated
	 */
	public String getStudentid() {
		return studentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentscores.studentID
	 * @param studentid  the value for experimentscores.studentID
	 * @mbggenerated
	 */
	public void setStudentid(String studentid) {
		this.studentid = studentid == null ? null : studentid.trim();
	}
}