package org.sinmem.bean;

public class Experimentclause {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experimentclause.experimentclauseNo
     *
     * @mbggenerated
     */
    private String experimentclauseno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experimentclause.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experimentclause.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experimentclause.bili
     *
     * @mbggenerated
     */
    private Float bili;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experimentclause.experimentNo
     *
     * @mbggenerated
     */
    private String experimentno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experimentclause.experimentclauseNo
     *
     * @return the value of experimentclause.experimentclauseNo
     *
     * @mbggenerated
     */
    public String getExperimentclauseno() {
        return experimentclauseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experimentclause.experimentclauseNo
     *
     * @param experimentclauseno the value for experimentclause.experimentclauseNo
     *
     * @mbggenerated
     */
    public void setExperimentclauseno(String experimentclauseno) {
        this.experimentclauseno = experimentclauseno == null ? null : experimentclauseno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experimentclause.title
     *
     * @return the value of experimentclause.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experimentclause.title
     *
     * @param title the value for experimentclause.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experimentclause.num
     *
     * @return the value of experimentclause.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experimentclause.num
     *
     * @param num the value for experimentclause.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experimentclause.bili
     *
     * @return the value of experimentclause.bili
     *
     * @mbggenerated
     */
    public Float getBili() {
        return bili;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experimentclause.bili
     *
     * @param bili the value for experimentclause.bili
     *
     * @mbggenerated
     */
    public void setBili(Float bili) {
        this.bili = bili;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experimentclause.experimentNo
     *
     * @return the value of experimentclause.experimentNo
     *
     * @mbggenerated
     */
    public String getExperimentno() {
        return experimentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experimentclause.experimentNo
     *
     * @param experimentno the value for experimentclause.experimentNo
     *
     * @mbggenerated
     */
    public void setExperimentno(String experimentno) {
        this.experimentno = experimentno == null ? null : experimentno.trim();
    }
}