package org.sinmem.bean;

public class Experimentclauses {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentclauses.experimentscoresNo
	 * @mbggenerated
	 */
	private String experimentscoresno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentclauses.experimentNo
	 * @mbggenerated
	 */
	private String experimentno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentclauses.experimentclauseNo
	 * @mbggenerated
	 */
	private String experimentclauseno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentclauses.title
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentclauses.evaluate
	 * @mbggenerated
	 */
	private String evaluate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentclauses.num
	 * @mbggenerated
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentclauses.bili
	 * @mbggenerated
	 */
	private Float bili;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column experimentclauses.score
	 * @mbggenerated
	 */
	private Float score;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentclauses.experimentscoresNo
	 * @return  the value of experimentclauses.experimentscoresNo
	 * @mbggenerated
	 */
	public String getExperimentscoresno() {
		return experimentscoresno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentclauses.experimentscoresNo
	 * @param experimentscoresno  the value for experimentclauses.experimentscoresNo
	 * @mbggenerated
	 */
	public void setExperimentscoresno(String experimentscoresno) {
		this.experimentscoresno = experimentscoresno == null ? null : experimentscoresno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentclauses.experimentNo
	 * @return  the value of experimentclauses.experimentNo
	 * @mbggenerated
	 */
	public String getExperimentno() {
		return experimentno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentclauses.experimentNo
	 * @param experimentno  the value for experimentclauses.experimentNo
	 * @mbggenerated
	 */
	public void setExperimentno(String experimentno) {
		this.experimentno = experimentno == null ? null : experimentno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentclauses.experimentclauseNo
	 * @return  the value of experimentclauses.experimentclauseNo
	 * @mbggenerated
	 */
	public String getExperimentclauseno() {
		return experimentclauseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentclauses.experimentclauseNo
	 * @param experimentclauseno  the value for experimentclauses.experimentclauseNo
	 * @mbggenerated
	 */
	public void setExperimentclauseno(String experimentclauseno) {
		this.experimentclauseno = experimentclauseno == null ? null : experimentclauseno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentclauses.title
	 * @return  the value of experimentclauses.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentclauses.title
	 * @param title  the value for experimentclauses.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentclauses.evaluate
	 * @return  the value of experimentclauses.evaluate
	 * @mbggenerated
	 */
	public String getEvaluate() {
		return evaluate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentclauses.evaluate
	 * @param evaluate  the value for experimentclauses.evaluate
	 * @mbggenerated
	 */
	public void setEvaluate(String evaluate) {
		this.evaluate = evaluate == null ? null : evaluate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentclauses.num
	 * @return  the value of experimentclauses.num
	 * @mbggenerated
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentclauses.num
	 * @param num  the value for experimentclauses.num
	 * @mbggenerated
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentclauses.bili
	 * @return  the value of experimentclauses.bili
	 * @mbggenerated
	 */
	public Float getBili() {
		return bili;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentclauses.bili
	 * @param bili  the value for experimentclauses.bili
	 * @mbggenerated
	 */
	public void setBili(Float bili) {
		this.bili = bili;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column experimentclauses.score
	 * @return  the value of experimentclauses.score
	 * @mbggenerated
	 */
	public Float getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column experimentclauses.score
	 * @param score  the value for experimentclauses.score
	 * @mbggenerated
	 */
	public void setScore(Float score) {
		this.score = score;
	}
}