package org.sinmem.bean;

public class Institute {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column institute.instituteNo
	 * @mbggenerated
	 */
	private String instituteno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column institute.instituteName
	 * @mbggenerated
	 */
	private String institutename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column institute.telephone
	 * @mbggenerated
	 */
	private String telephone;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column institute.instituteNo
	 * @return  the value of institute.instituteNo
	 * @mbggenerated
	 */
	public String getInstituteno() {
		return instituteno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column institute.instituteNo
	 * @param instituteno  the value for institute.instituteNo
	 * @mbggenerated
	 */
	public void setInstituteno(String instituteno) {
		this.instituteno = instituteno == null ? null : instituteno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column institute.instituteName
	 * @return  the value of institute.instituteName
	 * @mbggenerated
	 */
	public String getInstitutename() {
		return institutename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column institute.instituteName
	 * @param institutename  the value for institute.instituteName
	 * @mbggenerated
	 */
	public void setInstitutename(String institutename) {
		this.institutename = institutename == null ? null : institutename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column institute.telephone
	 * @return  the value of institute.telephone
	 * @mbggenerated
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column institute.telephone
	 * @param telephone  the value for institute.telephone
	 * @mbggenerated
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone == null ? null : telephone.trim();
	}
}