package org.sinmem.bean;

public class Major {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major.majorNo
	 * @mbggenerated
	 */
	private String majorno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major.majorName
	 * @mbggenerated
	 */
	private String majorname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column major.instituteNo
	 * @mbggenerated
	 */
	private String instituteno;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major.majorNo
	 * @return  the value of major.majorNo
	 * @mbggenerated
	 */
	public String getMajorno() {
		return majorno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major.majorNo
	 * @param majorno  the value for major.majorNo
	 * @mbggenerated
	 */
	public void setMajorno(String majorno) {
		this.majorno = majorno == null ? null : majorno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major.majorName
	 * @return  the value of major.majorName
	 * @mbggenerated
	 */
	public String getMajorname() {
		return majorname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major.majorName
	 * @param majorname  the value for major.majorName
	 * @mbggenerated
	 */
	public void setMajorname(String majorname) {
		this.majorname = majorname == null ? null : majorname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column major.instituteNo
	 * @return  the value of major.instituteNo
	 * @mbggenerated
	 */
	public String getInstituteno() {
		return instituteno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column major.instituteNo
	 * @param instituteno  the value for major.instituteNo
	 * @mbggenerated
	 */
	public void setInstituteno(String instituteno) {
		this.instituteno = instituteno == null ? null : instituteno.trim();
	}
}