package org.sinmem.bean;

public class S_c {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_c.studentID
	 * @mbggenerated
	 */
	private String studentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_c.cClassNo
	 * @mbggenerated
	 */
	private String cclassno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_c.courseNo
	 * @mbggenerated
	 */
	private String courseno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_c.score
	 * @mbggenerated
	 */
	private Float score;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_c.studentID
	 * @return  the value of s_c.studentID
	 * @mbggenerated
	 */
	public String getStudentid() {
		return studentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_c.studentID
	 * @param studentid  the value for s_c.studentID
	 * @mbggenerated
	 */
	public void setStudentid(String studentid) {
		this.studentid = studentid == null ? null : studentid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_c.cClassNo
	 * @return  the value of s_c.cClassNo
	 * @mbggenerated
	 */
	public String getCclassno() {
		return cclassno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_c.cClassNo
	 * @param cclassno  the value for s_c.cClassNo
	 * @mbggenerated
	 */
	public void setCclassno(String cclassno) {
		this.cclassno = cclassno == null ? null : cclassno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_c.courseNo
	 * @return  the value of s_c.courseNo
	 * @mbggenerated
	 */
	public String getCourseno() {
		return courseno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_c.courseNo
	 * @param courseno  the value for s_c.courseNo
	 * @mbggenerated
	 */
	public void setCourseno(String courseno) {
		this.courseno = courseno == null ? null : courseno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_c.score
	 * @return  the value of s_c.score
	 * @mbggenerated
	 */
	public Float getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_c.score
	 * @param score  the value for s_c.score
	 * @mbggenerated
	 */
	public void setScore(Float score) {
		this.score = score;
	}
	
	private String studentName;
	private String clazzName;
	private Integer education;

	public String getStudentName() {
		return studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public String getClazzName() {
		return clazzName;
	}

	public void setClazzName(String clazzName) {
		this.clazzName = clazzName;
	}

	public Integer getEducation() {
		return education;
	}

	public void setEducation(Integer education) {
		this.education = education;
	}
	
}