package org.sinmem.dao;

import java.util.ArrayList;

import org.apache.ibatis.annotations.Param;
import org.sinmem.bean.Courseclass;

public interface CourseclassMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courseclass
	 * @mbggenerated
	 */int deleteByPrimaryKey(@Param("courseno") String courseno,@Param("cclassno") String cclassno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courseclass
	 * @mbggenerated
	 */
	int insert(Courseclass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courseclass
	 * @mbggenerated
	 */
	int insertSelective(Courseclass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courseclass
	 * @mbggenerated
	 */Courseclass selectByPrimaryKey(@Param("courseno") String courseno,@Param("cclassno") String cclassno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courseclass
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Courseclass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courseclass
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Courseclass record);
	
	ArrayList<Courseclass> getCourseclassesByMajor(@Param("majorno")String majorno);
}