package org.sinmem.dao;

import org.apache.ibatis.annotations.Param;
import org.sinmem.bean.Experimentclauses;

public interface ExperimentclausesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experimentclauses
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("experimentscoresno") String experimentscoresno, @Param("experimentno") String experimentno, @Param("experimentclauseno") String experimentclauseno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experimentclauses
     *
     * @mbggenerated
     */
    int insert(Experimentclauses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experimentclauses
     *
     * @mbggenerated
     */
    int insertSelective(Experimentclauses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experimentclauses
     *
     * @mbggenerated
     */
    Experimentclauses selectByPrimaryKey(@Param("experimentscoresno") String experimentscoresno, @Param("experimentno") String experimentno, @Param("experimentclauseno") String experimentclauseno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experimentclauses
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Experimentclauses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experimentclauses
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Experimentclauses record);
}