package org.sinmem.dao;

import org.sinmem.bean.Experimentclause;

public interface ExperimentclauseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experimentclause
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String experimentclauseno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experimentclause
	 * @mbggenerated
	 */
	int insert(Experimentclause record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experimentclause
	 * @mbggenerated
	 */
	int insertSelective(Experimentclause record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experimentclause
	 * @mbggenerated
	 */
	Experimentclause selectByPrimaryKey(String experimentclauseno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experimentclause
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Experimentclause record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table experimentclause
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Experimentclause record);
}