package org.sinmem.dao;

import org.sinmem.bean.Institute;
import org.springframework.stereotype.Component;

@Component("InstituteMapper")
public interface InstituteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table institute
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String instituteno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table institute
	 * @mbggenerated
	 */
	int insert(Institute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table institute
	 * @mbggenerated
	 */
	int insertSelective(Institute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table institute
	 * @mbggenerated
	 */
	Institute selectByPrimaryKey(String instituteno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table institute
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Institute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table institute
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Institute record);
}