package org.sinmem.dao;

import java.util.ArrayList;

import org.sinmem.bean.Major;

public interface MajorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String majorno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major
	 * @mbggenerated
	 */
	int insert(Major record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major
	 * @mbggenerated
	 */
	int insertSelective(Major record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major
	 * @mbggenerated
	 */
	Major selectByPrimaryKey(String majorno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Major record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table major
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Major record);

	ArrayList<Major> selectMajorsByinstituteNo(String instituteNo);
}