package org.sinmem.dao;

import org.sinmem.bean.Student;
import org.sinmem.bean.Teacher;

public interface TeacherMapper extends UserMapper<Teacher>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated
	 */
	int insert(Teacher record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated
	 */
	int insertSelective(Teacher record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated
	 */
	Teacher selectByPrimaryKey(String userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Teacher record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Teacher record);
}